from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def _read_text(path: str) -> str:
    return (ROOT / path).read_text(encoding="utf-8")


def _normalized(text: str) -> str:
    return " ".join(text.split())


def test_github_templates_explain_trellm_and_tradearena_roles():
    required_snippets = {
        ".github/ISSUE_TEMPLATE/bug_report.yml": [
            "Report a reproducible TreLLM system or TradeArena leaderboard issue",
        ],
        ".github/ISSUE_TEMPLATE/research_extension.yml": [
            "Suggest an experiment that could strengthen the TreLLM system research or TradeArena leaderboard suite",
            "Paper, system, or leaderboard output",
        ],
        ".github/PULL_REQUEST_TEMPLATE.md": [
            "TreLLM system change",
            "TradeArena leaderboard or registry artifact update",
        ],
    }
    for path, snippets in required_snippets.items():
        text = _normalized(_read_text(path))
        for snippet in snippets:
            assert _normalized(snippet) in text


def test_contributor_docs_keep_system_and_leaderboard_identity_separate():
    required_snippets = {
        "docs/contributor_roadmap.md": [
            "TreLLM grows best when contributions make financial AI agents easier to evaluate, audit, reproduce, control, or extend.",
            "These contributions strengthen the TradeArena leaderboard and benchmark module.",
        ],
        "docs/community_participation.md": [
            "TreLLM should not describe itself as community-backed until public, reviewable participation exists.",
            "TradeArena leaderboard row",
            'early-stage research prototype with a public TradeArena leaderboard module',
        ],
    }
    for path, snippets in required_snippets.items():
        text = _normalized(_read_text(path))
        for snippet in snippets:
            assert _normalized(snippet) in text


def test_claim_and_validation_docs_use_trellm_for_system_claims():
    required_snippets = {
        "docs/benchmark_maturity.md": [
            "TreLLM should be presented as an early-stage research prototype until three forms of evidence exist in public:",
            "TradeArena can credibly describe its leaderboard as a niche benchmark only after the following minimum evidence exists:",
        ],
        "docs/claim_boundaries.md": [
            "TreLLM separates three kinds of claims.",
            "The TradeArena leaderboard rows carry explicit evidence labels:",
        ],
        "docs/external_validation_quickstart.md": [
            "TreLLM needs external evidence",
            "TradeArena leaderboard rows",
            "TreLLM should not claim community validation",
        ],
        "docs/external_validation.md": [
            "External validation is the evidence that makes TreLLM more than a maintainer-run demo.",
            "accepted validations can be linked from the TradeArena leaderboard registry or release notes.",
        ],
        "docs/academic_report_plan.md": [
            "TreLLM currently has technical documentation and TradeArena leaderboard artifacts.",
            "TreLLM can run auditable offline and paper/sandbox agent loops",
            "TradeArena can compare agents under shared risk and execution assumptions",
        ],
        "docs/demo_matrix.md": [
            "This matrix maps TreLLM capabilities to hands-on repository artifacts.",
            "how TreLLM should progress from paper research to broker-review exports",
        ],
    }
    for path, snippets in required_snippets.items():
        text = _normalized(_read_text(path))
        for snippet in snippets:
            assert _normalized(snippet) in text


def test_launch_and_pages_sources_use_trellm_for_public_positioning():
    required_snippets = {
        "docs/blog/why_llm_trading_agents_need_audit_benchmarks.md": [
            "TreLLM takes a different view. It treats a financial AI agent as an auditable decision-making system:",
            "TreLLM renders this as a browser-readable audit report",
            "TradeArena is its public leaderboard and benchmark module",
        ],
        "docs/launch/README.md": [
            "# TreLLM Project Metadata",
            "TreLLM's public positioning is:",
            "TreLLM turns every financial-agent decision into a traceable trajectory:",
            "LLM-driven trading audit and control system with replayable trajectories, risk gates, paper execution, and TradeArena leaderboard artifacts.",
        ],
        "docs/launch/pages_demo.md": [
            "TreLLM publishes the project landing page and quickstart showcase",
        ],
        ".github/workflows/pages.yml": [
            "TreLLM static demo generated by:",
        ],
        "scripts/run_showcase.py": [
            'description="Build the public-facing TreLLM showcase."',
            "print(\"TreLLM showcase\", flush=True)",
            "<title>TreLLM - Trading Audit And Control Showcase</title>",
            "<h1>TreLLM: LLM Trading Audit And Control</h1>",
            "<title>TreLLM 3-Minute Demo Video</title>",
            "<h1>TreLLM 3-Minute Demo Video</h1>",
            "<h1>TreLLM Showcase: Quickstart Tour</h1>",
            'aria-label="TreLLM 3-minute demo video"',
            "What TreLLM is not:",
            "TradeArena is the public leaderboard and benchmark module",
        ],
        "scripts/build_demo_video.py": [
            'draw.text((72, 36), "TreLLM", fill="#ccfbf1", font=fonts["brand"])',
        ],
        "scripts/validate_demo_artifacts.py": [
            'description="Validate required TreLLM demo artifacts."',
        ],
    }
    for path, snippets in required_snippets.items():
        text = _normalized(_read_text(path))
        for snippet in snippets:
            assert _normalized(snippet) in text


def test_developer_docs_use_trellm_for_system_surfaces():
    required_snippets = {
        "docs/artifact_portability.md": [
            "TreLLM artifacts should be easy to move between local machines",
        ],
        "docs/observability.md": [
            "TreLLM trajectories are already structured logs.",
        ],
        "docs/plugin_development.md": [
            "TreLLM plugins are small Python objects that implement one narrow protocol:",
        ],
        "docs/extension_walkthrough.md": [
            "TreLLM is designed around narrow protocol surfaces.",
        ],
        "docs/public_artifact_privacy.md": [
            "TreLLM separates local debugging records from public TradeArena leaderboard artifacts.",
        ],
        "docs/execution_model_boundaries.md": [
            "TreLLM separates execution assumptions into explicit import surfaces:",
        ],
        "docs/schemas.md": [
            "# TreLLM Schemas",
            "TreLLM treats a financial AI agent as an auditable reliability lifecycle",
        ],
        "docs/retail_planning.md": [
            "TreLLM includes an offline-friendly planning layer",
        ],
        "docs/market_rules.md": [
            "TreLLM's default simulator is market-agnostic.",
            "TreLLM now exposes these as testable rule-package helpers",
        ],
        "docs/financial_audit_agent_benchmark.md": [
            "TreLLM skills are evaluated as audit workflows, not as trading strategies.",
        ],
        "docs/execution_model.md": [
            "TreLLM's execution layer is a configurable paper-execution stress model.",
        ],
    }
    for path, snippets in required_snippets.items():
        text = _normalized(_read_text(path))
        for snippet in snippets:
            assert _normalized(snippet) in text


def test_generated_public_copy_sources_use_trellm_system_identity():
    required_snippets = {
        "docs/agent_skills.md": [
            "# TreLLM Agent Skills",
            "TreLLM agent skills are repository workflow templates for audit",
        ],
        "scripts/build_demo_video.py": [
            '"title": "TreLLM in 3 Minutes"',
            "TreLLM separates intended allocation from what the market simulator can actually fill.",
            '"title": "What TreLLM is for"',
            'description="Build a captioned 3-minute TreLLM demo video."',
            '"TreLLM showcase"',
        ],
        "scripts/score_skill_task_report.py": [
            "# TreLLM Skill Task Matrix",
            "TreLLM skills help agents inspect, reproduce, audit, and extend TradeArena leaderboard artifacts.",
        ],
        "scripts/scan_public_artifacts.py": [
            "Scan public TreLLM artifacts for raw prompt/response or secret leakage.",
        ],
        "scripts/build_benchmark_page.py": [
            "TreLLM is a financial-agent reliability audit framework. TradeArena is the",
            "benchmark card and leaderboard surface, not a profitability claim.",
        ],
        "docs/results/benchmark_v0_2.md": [
            "TreLLM is a financial-agent reliability audit framework. TradeArena is the benchmark",
            "card and leaderboard surface, not a profitability claim.",
        ],
        "docs/benchmark_submissions.md": [
            "TradeArena accepts redacted leaderboard manifests so users can compare runs",
        ],
        "docs/launch/discussion_seeds.md": [
            "TreLLM currently records observation, signals, proposed decisions, approved",
            "If you use TreLLM in a class, project, or internal evaluation",
        ],
    }
    for path, snippets in required_snippets.items():
        text = _normalized(_read_text(path))
        for snippet in snippets:
            assert _normalized(snippet) in text


def test_release_notes_use_trellm_for_system_release_positioning():
    required_snippets = {
        "docs/launch/release_notes_v0.2.1.md": [
            "TreLLM v0.2.1 is a patch-release candidate focused on evidence quality",
            "TradeArena remains the public leaderboard and benchmark module",
        ],
        "docs/launch/release_notes_v0.2.0.md": [
            "TreLLM v0.2.0 is the first protocol-focused release for the TradeArena benchmark module.",
        ],
        "docs/launch/release_notes_v0.1.0.md": [
            "TreLLM v0.1.0 is the first public benchmark release for evaluating LLM",
            "TreLLM is not a live trading bot and does not promise profitable trading.",
        ],
        "docs/launch/release_notes_v0.1.1.md": [
            "TreLLM v0.1.1 is a small maintenance release focused on making execution",
        ],
        "docs/launch/release_notes_v0.1.2.md": [
            "TreLLM v0.1.2 is the first PyPI-ready release under the",
        ],
    }
    for path, snippets in required_snippets.items():
        text = _normalized(_read_text(path))
        for snippet in snippets:
            assert _normalized(snippet) in text


def test_citation_and_research_report_keep_system_and_leaderboard_identity_separate():
    required_snippets = {
        "CITATION.cff": [
            "If you use TreLLM in research, please cite the arXiv technical report.",
            "If you use TradeArena leaderboard artifacts or a specific software release",
            "title: \"TreLLM: An LLM-Driven Trading Audit and Control System with TradeArena Leaderboard Artifacts\"",
            "title: \"Representation Signatures and Risk-Feedback Alignment in LLM Trading Agents\"",
        ],
        "docs/research_report.md": [
            "The public technical report for TreLLM research claims and TradeArena leaderboard artifacts is:",
            "Use the report for research claims about representation signatures",
            "Use repository release citations for software-version-specific reproduction.",
        ],
        "README.md": [
            "If you use TreLLM in research or cite TradeArena leaderboard artifacts, please cite the technical report:",
        ],
        "pyproject.toml": [
            'authors = [{ name = "TreLLM Contributors" }]',
        ],
    }
    for path, snippets in required_snippets.items():
        text = _normalized(_read_text(path))
        for snippet in snippets:
            assert _normalized(snippet) in text
