"""Tool plugins for simulation, features, risk, optimization, and backtesting."""

from tradearena.execution import (
    CalibratedOrderSimulator,
    FillReplayOrderSimulator,
    QuoteReplayOrderSimulator,
    RealisticOrderSimulator,
    SimpleOrderSimulator,
    load_replay_fills_csv,
)
from tradearena.tools.backtester import Backtester, BacktestResult
from tradearena.tools.broker_export import (
    AlpacaPaperExportAdapter,
    AlpacaPaperOrder,
    BrokerAdapter,
    BrokerAdapterContractError,
    BrokerAdapterMode,
    BrokerOrderStatus,
    BrokerApproval,
    BrokerReconciliationSummary,
    BrokerResponse,
    BrokerSafetyConfig,
    DryRunBrokerAdapter,
    build_broker_approval_artifact,
    broker_approval_from_artifact,
    broker_safety_from_approval_artifact,
    reconcile_broker_responses,
    validate_broker_approval_artifact,
    validate_broker_approval_artifact_file,
    validate_broker_handoff_artifact,
    validate_broker_handoff_artifact_file,
    validate_broker_response_artifact,
    validate_broker_response_artifact_file,
    write_broker_response_artifact,
)
from tradearena.tools.calibration import (
    ExecutionCalibrationConfig,
    discover_ohlcv_files,
    summarize_execution_calibration,
    write_calibration_json,
    write_calibration_markdown,
)
from tradearena.tools.features import RollingFeatureStore
from tradearena.tools.futures import FuturesContractMetadata, FuturesRollRiskEngine
from tradearena.tools.market_rules import (
    MarketRule,
    MarketRuleDecision,
    MarketRulePackage,
    MarketRuleState,
    PackageMarketRule,
    ashare_rule_package,
    crypto_rule_package,
    explain_market_rule_decision,
    futures_rule_package,
    hong_kong_rule_package,
    liquidity_halt_rule_package,
    market_rule_from_package,
    review_market_rule_order,
    validate_market_rule_plugin,
)
from tradearena.tools.optimizer import EqualRiskBudgetOptimizer
from tradearena.tools.risk import RiskCalculator

__all__ = [
    "AlpacaPaperExportAdapter",
    "AlpacaPaperOrder",
    "BacktestResult",
    "Backtester",
    "BrokerAdapter",
    "BrokerAdapterContractError",
    "BrokerAdapterMode",
    "BrokerOrderStatus",
    "BrokerApproval",
    "BrokerReconciliationSummary",
    "BrokerResponse",
    "BrokerSafetyConfig",
    "CalibratedOrderSimulator",
    "DryRunBrokerAdapter",
    "ExecutionCalibrationConfig",
    "EqualRiskBudgetOptimizer",
    "FillReplayOrderSimulator",
    "FuturesContractMetadata",
    "FuturesRollRiskEngine",
    "MarketRule",
    "MarketRuleDecision",
    "MarketRulePackage",
    "MarketRuleState",
    "PackageMarketRule",
    "QuoteReplayOrderSimulator",
    "RiskCalculator",
    "RollingFeatureStore",
    "RealisticOrderSimulator",
    "SimpleOrderSimulator",
    "discover_ohlcv_files",
    "load_replay_fills_csv",
    "summarize_execution_calibration",
    "write_calibration_json",
    "write_calibration_markdown",
    "ashare_rule_package",
    "crypto_rule_package",
    "explain_market_rule_decision",
    "futures_rule_package",
    "hong_kong_rule_package",
    "liquidity_halt_rule_package",
    "market_rule_from_package",
    "review_market_rule_order",
    "validate_market_rule_plugin",
    "build_broker_approval_artifact",
    "broker_approval_from_artifact",
    "broker_safety_from_approval_artifact",
    "reconcile_broker_responses",
    "validate_broker_approval_artifact",
    "validate_broker_approval_artifact_file",
    "validate_broker_handoff_artifact",
    "validate_broker_handoff_artifact_file",
    "validate_broker_response_artifact",
    "validate_broker_response_artifact_file",
    "write_broker_response_artifact",
]
